insert into users (u_id, username, password) values (default, 'rbalham0', '$2a$04$1nDG4nS0dqE/JQ/RML2JR.B679qPGdbA5e8C6qrIXzETJDkEQjye.');
insert into users (u_id, username, password) values (default, 'hsansun1', '$2a$04$dfbzMo/swEjkNIswiAxpDuElZnFR/GA3YCaZfsnMqz9SvLwt7EsOu');
insert into users (u_id, username, password) values (default, 'hwhatson2', '$2a$04$ZJTkx25xLQ.lWbUH0GKQ3uEeltDlkNlM0NEeTVTEyyk3yf6WxK9O6');
insert into users (u_id, username, password) values (default, 'zseely3', '$2a$04$zbW7RRDTYbp2.NcG/GiuzO3T8/CYDWd5WVi/YWuXKNZrf4g3faMfW');
insert into users (u_id, username, password) values (default, 'ktraite4', '$2a$04$e63/rUZXpvDx3dwc4NYsZeOX/6d3j8giYPu0w30sIqkw3ccA3BRX.');
insert into users (u_id, username, password) values (default, 'blivingstone5', '$2a$04$K.zOMAc9K9vRChNMKw8uMe4Xrz0r.323fSdIT2D6Hey7TGFv7wbTG');
insert into users (u_id, username, password) values (default, 'ncolwell6', '$2a$04$uxOuMONOSCyBBsVHJ9a/XeY.Q2suK52leGp5MkfMruRdK0qRSnyLO');
insert into users (u_id, username, password) values (default, 'eoughton7', '$2a$04$IPf5i/OS7qqvSc0NiHWqiOLzLCq1/Cvys88AZhMBaNKrG.8WbegTS');
insert into users (u_id, username, password) values (default, 'rduplain8', '$2a$04$AXlFNgzk9NPD1GV9CDil5eziyIKNCYho.rA0oaD8PRB0sXKyZJWJO');
insert into users (u_id, username, password) values (default, 'hjellman9', '$2a$04$WmMHehJaKJPZrCOjtGusuOeDVn6SH4WW6Opo7vPV8Lnf1rc9vGYm.');
insert into users (u_id, username, password) values (default, 'mandrosika', '$2a$04$0nDu2JyZ5ZLLVpMo8DqrC.S7Vjw75HfwnqWF5c8wCFmQowdO1kZA6');
insert into users (u_id, username, password) values (default, 'lsummerscalesb', '$2a$04$XC/p6WNgVXhJX2yyXuKCPuJcSUTsUsAnMWhWPYdVJelJ5LDnT2KUG');
insert into users (u_id, username, password) values (default, 'ijoustc', '$2a$04$Z.ObFbeEt5.qje1lJghFxexUi.QVz2qbr9T9rqnFSAY7eGXIUPdaK');
insert into users (u_id, username, password) values (default, 'jhuettd', '$2a$04$NBKOe8TzxqpogcmNA1ek0uPExFNuiN5rMtLGDwFXRn5puJfJTM0Yi');
insert into users (u_id, username, password) values (default, 'eboribale', '$2a$04$hgXk2GyDkTlIqhjnEpFR3Ok484q9HszkF0ORJlYtOUnhib5t89z9y');
insert into users (u_id, username, password) values (default, 'fcellierf', '$2a$04$I7NAgNwlSk7JY5b86.aH/uZ4Dk4Bu3NIGmsCXRACIbFeWZ8/mQT.m');
insert into users (u_id, username, password) values (default, 'echavring', '$2a$04$MswvCCjmuB0G5pb8128AD.kKnl2xUP.EwiWrhYGSwrDd/RO7F.c82');
insert into users (u_id, username, password) values (default, 'pdrinkelh', '$2a$04$5f88Ed7ogaSOvjFlsaatoeP1iPDR6hYiVnLtpVTCypERlEuj4n9Tq');
insert into users (u_id, username, password) values (default, 'kbehnincki', '$2a$04$SykDN7MHyL5vNwxVFgRBNuBZr5kxVbNW5/A4xlqeTghqWp2iKw0Du');
insert into users (u_id, username, password) values (default, 'rbuckyj', '$2a$04$3jgZzY.fNpJwtTCx7r9Gi.pBp.8g5X0rMdJhk.O3iiLoeb2zUNZbK');
insert into users (u_id, username, password) values (default, 'dsteartk', '$2a$04$v7p6reejOAFu1LwW7b6ESejeD8Vn5cQsA5gYs.dcmOKCzHYYoWi.G');
insert into users (u_id, username, password) values (default, 'fsaml', '$2a$04$c/1eSY5Pf.0Dz/EGMf3HBODgfwahHlh37WcfGRLW320cwA0Cm52bW');
insert into users (u_id, username, password) values (default, 'rkunertm', '$2a$04$nRmc4sNc5u3.Sc9v.jqmSu72yNApn5mbw2oPZr/TUaBVVM1o1oYhK');
insert into users (u_id, username, password) values (default, 'jjoslingn', '$2a$04$CC.WYoyM7R/lica01nVGsONOZvkWLCqHGfKnh4SVKLLJFkXrFKyQi');
insert into users (u_id, username, password) values (default, 'lrathborneo', '$2a$04$/h6pQiK1rWCKSTpg62VQHuwrvwQ0HP1TqlL3RDsU013DXFpmX1y1S');
insert into users (u_id, username, password) values (default, 'lbeckinghamp', '$2a$04$Ck04OW9KHuLgtkIdHx3jJecgUUCTadYJnyFy4nf2Y/Dna9neFqSGG');
insert into users (u_id, username, password) values (default, 'pvandenbroekq', '$2a$04$AXpVCL.jYeqPLzn1YbZtxeliyEUUQcncaVNYfv2O//v9U/iOlxp0u');
insert into users (u_id, username, password) values (default, 'eelcoater', '$2a$04$bILbeEHkzd9izHiFHG0tpO0UA24aXm8yigrshLMyTg8uj8b7uEBuS');
insert into users (u_id, username, password) values (default, 'lramages', '$2a$04$Q4UibxJjbjyGB5DKq1hHOesUvtpP3fWbXUosUPPgcv1CF8surSC4O');
insert into users (u_id, username, password) values (default, 'treayt', '$2a$04$7Pk3UN3aT0sOxvQePoK6EegAr.qzO.8DCMhGLH36YDanxQZQKz/kG');
insert into users (u_id, username, password) values (default, 'sschurichtu', '$2a$04$5IVhY4KghfitqiCPvz0eguu.XShkynPy8E1aHbdCi3gA.UtAS112.');
insert into users (u_id, username, password) values (default, 'rprintv', '$2a$04$AUGZ7whdG4shuhqTqBIk1.pWdMBVilYqgXM6Uf8cBP4E0WY72Y8Zu');
insert into users (u_id, username, password) values (default, 'lmugridgew', '$2a$04$oNDbsSA.mWC2nXgxw/hG3.2LeYztSt4W4/2lY9d9c1pGMMxmdTgnO');
insert into users (u_id, username, password) values (default, 'aprydex', '$2a$04$qE0Rjr2h4Hn9MpFGKyPxteVACyQsW.BPsXM.m0JkgNn9osJTBW3Ti');
insert into users (u_id, username, password) values (default, 'egravesony', '$2a$04$MXNJTdjdX3mCfLfEVIARbu6TFmEyUbTBS.3IGYE9p64Pzcy62HWX6');
insert into users (u_id, username, password) values (default, 'rdessantz', '$2a$04$TA5fin2vs2kernzGaVK7SuT71G.poqM.rAa1qrUMlv3zFN9zCBMSu');
insert into users (u_id, username, password) values (default, 'akyle10', '$2a$04$YYbD8BMD6SYT4ZZfsZiuie4pBxpsKuZlbm3G07p3UrYJ5L14oJG7i');
insert into users (u_id, username, password) values (default, 'lfiddy11', '$2a$04$tloQvcyDYG89t82F9OKmNecLEcPnHslJjR6whgoOPtzUJf8KV4ujK');
insert into users (u_id, username, password) values (default, 'kjee12', '$2a$04$mISOqfGZmpH3LtXqqEk3U.ATNdOkP.rSA5WNCy9g0uRCS1kFv0.Ka');
insert into users (u_id, username, password) values (default, 'keyres13', '$2a$04$I78WZiPs3OxhSPIVUUupJuIVt4F.JsUE3F5G5oC6DsIndn55viohO');
insert into users (u_id, username, password) values (default, 'sfitzharris14', '$2a$04$HLiZ3cNUZXy6Co2z/d2yCuPA3Wh4w.2R3L8lCfLruDYuT5DfkDtZe');
insert into users (u_id, username, password) values (default, 'sswyre15', '$2a$04$V4G0WrDdF987q83topXiWuVDyaHR8McY0stvQVjJfFGJegshb1j8q');
insert into users (u_id, username, password) values (default, 'kguillotin16', '$2a$04$Lv4OyZXTmvaHT6MCUxteDeLjXh/pCzwn5uq6Vx2SdzR3USRBH2vvO');
insert into users (u_id, username, password) values (default, 'cjenyns17', '$2a$04$Wkt3iIpaad99GvkwDXx4sui8IlBGeSrIfnLQpfIgMuu65JJtI4/iO');
insert into users (u_id, username, password) values (default, 'pdelue18', '$2a$04$2I7Lu59i5OuLqqW4Sta5cOMGHkh39OdG8TdXn/7yQ6cjLVYvprZGi');
insert into users (u_id, username, password) values (default, 'pbartul19', '$2a$04$yPWGR5TctJC44QIhNFb0TuwtvqL.dcFhBIXgjvS0n7LuxdMaU28eS');
insert into users (u_id, username, password) values (default, 'mpreuvost1a', '$2a$04$6PfHGHcaJl68KCOgjQnSO.X7YfI8HltcZDlb2PY6P.c44LoFmrqHi');
insert into users (u_id, username, password) values (default, 'owink1b', '$2a$04$V0f.7HSm6Nut8.CFSmw/hOta0pgFTTCXP/ZpXKyYGWesmeHAoqz1.');
insert into users (u_id, username, password) values (default, 'jmilverton1c', '$2a$04$IarBquIIFMRXM5Sq/HdAluQqhvN1FCEyJxSk6hEGt9wSxWZT4x0sS');
insert into users (u_id, username, password) values (default, 'pgianolo1d', '$2a$04$eNpEsnzEKLTJRm9i99PT6e7DF5p4JNd9WmtwVqg0CbdKt4/Mc8Jxe');


--profiles mock data
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 109, 70.5, 2.5, 1361.4, 44.7);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 51, 220.9, 1.4, 1452.0, 6.9);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 136, 55.9, 2.7, 1900.4, 45.1);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 98, 189.4, 1.6, 1934.9, 20.2);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 125, 110.9, 3.7, 1978.3, 32.9);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 83, 202.6, 1.4, 1111.2, 14.8);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 88, 99.8, 3.3, 1070.5, 26.6);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 76, 188.7, 2.5, 1572.3, 31.2);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 63, 208.5, 1.6, 1866.6, 43.4);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 70, 83.0, 2.1, 1413.0, 16.7);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 142, 250.4, 1.6, 1000.7, 34.1);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 129, 117.6, 1.5, 1888.1, 24.5);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 138, 188.5, 1.5, 1794.5, 19.9);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 107, 150.8, 1.2, 1971.4, 30.3);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 90, 111.1, 2.2, 1755.6, 44.4);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 139, 296.2, 1.3, 1648.5, 29.0);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 137, 175.9, 2.5, 1500.7, 30.5);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 115, 132.3, 1.4, 1076.0, 5.8);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 127, 174.4, 3.3, 1822.1, 18.1);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 131, 296.6, 4.0, 1508.3, 21.7);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 127, 56.8, 1.7, 1147.9, 27.1);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 89, 245.3, 2.1, 1318.4, 3.9);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 59, 143.4, 1.2, 1007.4, 14.1);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 111, 53.7, 2.7, 1047.1, 35.9);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 143, 88.1, 2.1, 1040.9, 28.1);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 99, 284.6, 2.5, 1988.0, 49.2);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 141, 232.7, 2.7, 1765.0, 1.3);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 109, 131.8, 1.0, 1808.1, 42.9);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 52, 256.0, 3.5, 1299.3, 44.9);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 90, 250.7, 1.7, 1823.3, 6.2);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 148, 238.8, 3.9, 1158.1, 17.9);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 110, 235.1, 3.6, 1693.2, 27.8);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 71, 148.0, 3.6, 1329.4, 31.3);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 148, 75.7, 2.4, 1347.9, 21.6);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 80, 288.8, 1.1, 1928.0, 14.7);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 94, 113.4, 3.7, 1455.5, 43.4);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 112, 274.3, 3.9, 1943.2, 19.9);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 111, 262.6, 3.5, 1374.6, 40.6);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 78, 54.9, 3.7, 1713.5, 6.0);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 68, 182.0, 1.3, 1829.3, 15.0);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 122, 148.8, 2.3, 1663.4, 27.0);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 149, 125.9, 1.6, 1599.1, 26.2);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 123, 97.5, 3.0, 1344.8, 32.1);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 78, 190.0, 2.7, 1831.3, 40.2);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 67, 95.6, 3.2, 1579.1, 7.3);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, true, 58, 214.3, 3.0, 1766.5, 28.0);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 83, 280.7, 2.3, 1869.8, 44.8);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 62, 218.2, 2.0, 1658.5, 20.3);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 62, 156.5, 2.7, 1198.8, 34.4);
insert into profiles (p_id, gender, height, weight, activity, calorie_goal, u_id) values (default, false, 126, 273.5, 1.5, 1861.0, 30.2);


--foods dummy data
INSERT INTO food (food_name, calories) VALUES ('Apple', 95);
INSERT INTO food (food_name, calories) VALUES ('Banana', 105);
INSERT INTO food (food_name, calories) VALUES ('Orange', 62);
INSERT INTO food (food_name, calories) VALUES ('Strawberry', 4);
INSERT INTO food (food_name, calories) VALUES ('Blueberry', 85);
INSERT INTO food (food_name, calories) VALUES ('Grapes', 62);
INSERT INTO food (food_name, calories) VALUES ('Watermelon', 85);
INSERT INTO food (food_name, calories) VALUES ('Peach', 59);
INSERT INTO food (food_name, calories) VALUES ('Cherry', 50);
INSERT INTO food (food_name, calories) VALUES ('Pineapple', 82);
INSERT INTO food (food_name, calories) VALUES ('Mango', 99);
INSERT INTO food (food_name, calories) VALUES ('Papaya', 59);
INSERT INTO food (food_name, calories) VALUES ('Kiwi', 42);
INSERT INTO food (food_name, calories) VALUES ('Lemon', 17);
INSERT INTO food (food_name, calories) VALUES ('Lime', 20);
INSERT INTO food (food_name, calories) VALUES ('Plum', 30);
INSERT INTO food (food_name, calories) VALUES ('Apricot', 17);
INSERT INTO food (food_name, calories) VALUES ('Grapefruit', 52);
INSERT INTO food (food_name, calories) VALUES ('Pomegranate', 234);
INSERT INTO food (food_name, calories) VALUES ('Cantaloupe', 60);
INSERT INTO food (food_name, calories) VALUES ('Honeydew', 61);
INSERT INTO food (food_name, calories) VALUES ('Avocado', 234);
INSERT INTO food (food_name, calories) VALUES ('Tomato', 22);
INSERT INTO food (food_name, calories) VALUES ('Cucumber', 16);
INSERT INTO food (food_name, calories) VALUES ('Bell Pepper', 24);
INSERT INTO food (food_name, calories) VALUES ('Carrot', 25);
INSERT INTO food (food_name, calories) VALUES ('Broccoli', 55);
INSERT INTO food (food_name, calories) VALUES ('Cauliflower', 25);
INSERT INTO food (food_name, calories) VALUES ('Spinach', 23);
INSERT INTO food (food_name, calories) VALUES ('Kale', 33);
INSERT INTO food (food_name, calories) VALUES ('Lettuce', 5);
INSERT INTO food (food_name, calories) VALUES ('Onion', 44);
INSERT INTO food (food_name, calories) VALUES ('Garlic', 4);
INSERT INTO food (food_name, calories) VALUES ('Potato', 163);
INSERT INTO food (food_name, calories) VALUES ('Sweet Potato', 112);
INSERT INTO food (food_name, calories) VALUES ('Corn', 96);
INSERT INTO food (food_name, calories) VALUES ('Peas', 62);
INSERT INTO food (food_name, calories) VALUES ('Green Bean', 31);
INSERT INTO food (food_name, calories) VALUES ('Zucchini', 33);
INSERT INTO food (food_name, calories) VALUES ('Eggplant', 35);
INSERT INTO food (food_name, calories) VALUES ('Mushroom', 15);
INSERT INTO food (food_name, calories) VALUES ('Pumpkin', 49);
INSERT INTO food (food_name, calories) VALUES ('Squash', 36);
INSERT INTO food (food_name, calories) VALUES ('Asparagus', 20);
INSERT INTO food (food_name, calories) VALUES ('Brussels Sprouts', 38);
INSERT INTO food (food_name, calories) VALUES ('Celery', 6);
INSERT INTO food (food_name, calories) VALUES ('Radish', 1);
INSERT INTO food (food_name, calories) VALUES ('Beet', 43);
INSERT INTO food (food_name, calories) VALUES ('Turnip', 34);
INSERT INTO food (food_name, calories) VALUES ('Parsnip', 100);
INSERT INTO food (food_name, calories) VALUES ('Artichoke', 60);
INSERT INTO food (food_name, calories) VALUES ('Okra', 33);
INSERT INTO food (food_name, calories) VALUES ('Leek', 61);
INSERT INTO food (food_name, calories) VALUES ('Rhubarb', 26);
INSERT INTO food (food_name, calories) VALUES ('Jicama', 46);
INSERT INTO food (food_name, calories) VALUES ('Cabbage', 22);
INSERT INTO food (food_name, calories) VALUES ('Egg', 78);
INSERT INTO food (food_name, calories) VALUES ('Chicken Breast', 165);
INSERT INTO food (food_name, calories) VALUES ('Turkey Breast', 125);
INSERT INTO food (food_name, calories) VALUES ('Salmon', 208);
INSERT INTO food (food_name, calories) VALUES ('Tuna', 132);
INSERT INTO food (food_name, calories) VALUES ('Shrimp', 99);
INSERT INTO food (food_name, calories) VALUES ('Lobster', 129);
INSERT INTO food (food_name, calories) VALUES ('Crab', 97);
INSERT INTO food (food_name, calories) VALUES ('Beef Steak', 679);
INSERT INTO food (food_name, calories) VALUES ('Pork Chop', 257);
INSERT INTO food (food_name, calories) VALUES ('Bacon', 42);
INSERT INTO food (food_name, calories) VALUES ('Ham', 145);
INSERT INTO food (food_name, calories) VALUES ('Lamb', 294);
INSERT INTO food (food_name, calories) VALUES ('Duck', 337);
INSERT INTO food (food_name, calories) VALUES ('Venison', 151);
INSERT INTO food (food_name, calories) VALUES ('Cheddar Cheese', 113);
INSERT INTO food (food_name, calories) VALUES ('Mozzarella Cheese', 85);
INSERT INTO food (food_name, calories) VALUES ('Yogurt', 59);
INSERT INTO food (food_name, calories) VALUES ('Milk', 103);
INSERT INTO food (food_name, calories) VALUES ('Butter', 102);
INSERT INTO food (food_name, calories) VALUES ('Cream', 52);
INSERT INTO food (food_name, calories) VALUES ('Ice Cream', 137);
INSERT INTO food (food_name, calories) VALUES ('Chocolate', 208);
INSERT INTO food (food_name, calories) VALUES ('Bread', 79);
INSERT INTO food (food_name, calories) VALUES ('Pasta', 131);
INSERT INTO food (food_name, calories) VALUES ('Rice', 206);
INSERT INTO food (food_name, calories) VALUES ('Oats', 154);
INSERT INTO food (food_name, calories) VALUES ('Quinoa', 222);
INSERT INTO food (food_name, calories) VALUES ('Chickpeas', 164);
INSERT INTO food (food_name, calories) VALUES ('Lentils', 230);
INSERT INTO food (food_name, calories) VALUES ('Black Beans', 227);
INSERT INTO food (food_name, calories) VALUES ('Kidney Beans', 225);
INSERT INTO food (food_name, calories) VALUES ('Peanut Butter', 190);
INSERT INTO food (food_name, calories) VALUES ('Almonds', 164);
INSERT INTO food (food_name, calories) VALUES ('Walnuts', 185);
INSERT INTO food (food_name, calories) VALUES ('Cashews', 157);
INSERT INTO food (food_name, calories) VALUES ('Pistachios', 159);
INSERT INTO food (food_name, calories) VALUES ('Sunflower Seeds', 204);
INSERT INTO food (food_name, calories) VALUES ('Pumpkin Seeds', 151);


--calorie_track table dummy data
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 62, 38, 4.6, '2024-03-17');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 47, 18, 4.6, '2024-01-21');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 62, 26, 3.0, '2024-02-02');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 11, 11, 4.7, '2024-05-03');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 48, 28, 4.7, '2024-02-11');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 75, 40, 2.2, '2024-07-08');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 79, 24, 4.9, '2024-04-20');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 53, 16, 2.8, '2024-04-08');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 25, 33, 1.6, '2024-06-14');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 49, 48, 3.1, '2024-04-29');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 91, 23, 3.1, '2024-07-11');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 50, 25, 3.5, '2024-06-27');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 19, 4, 4.0, '2024-02-11');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 22, 13, 3.0, '2024-06-30');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 68, 7, 2.2, '2024-06-19');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 31, 41, 1.5, '2024-04-29');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 60, 25, 4.2, '2024-04-30');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 82, 32, 3.7, '2024-01-04');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 67, 5, 2.9, '2024-03-25');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 77, 6, 2.3, '2024-04-01');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 60, 9, 2.9, '2024-03-09');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 48, 29, 3.6, '2024-03-22');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 60, 42, 4.1, '2024-06-25');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 28, 41, 4.2, '2024-05-02');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 5, 46, 3.5, '2024-05-12');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 38, 47, 3.7, '2024-01-28');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 62, 20, 3.8, '2024-07-10');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 35, 5, 3.9, '2024-04-27');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 52, 30, 1.3, '2024-03-29');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 55, 26, 4.7, '2024-01-18');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 28, 8, 3.5, '2024-06-16');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 33, 28, 1.4, '2024-04-07');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 69, 5, 3.3, '2024-03-08');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 53, 45, 4.3, '2024-05-09');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 22, 25, 2.2, '2024-06-21');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 78, 32, 2.1, '2024-05-30');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 39, 7, 4.4, '2024-02-05');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 46, 48, 4.8, '2024-01-29');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 27, 42, 3.4, '2024-07-12');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 20, 19, 3.2, '2024-03-16');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 72, 39, 1.5, '2024-01-11');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 10, 49, 4.4, '2024-01-03');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 5, 47, 3.3, '2024-04-12');
insert into calorie_track (c_id, f_id, u_id, serving, log_date) values (default, 36, 48, 3.5, '2024-05-26');

